language: go
sudo: false
go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -test.v
  - chmod +x go.test.sh && ./go.test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)